version: "3.9"

networks:
    network_okrdv:
        external: true

#networks:
#  network_okrdv:
#    external:
#      name: "network_okrdv"

services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - network_okrdv

  pg-admin:
    image: dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050

    ports:
      - "5050:5050"
    networks:
      - network_okrdv:
        - ipv4_address: 10.0.0.4

volumes:
  data: